API Updates
checkout/checkout-sdk-net pull request #314
Opened 2023-06-05 12:59 UTC by armando-rodriguez-cko

API Updates
- Add local_schemes and deprecate scheme_local
- Feat(issuing): simulate preauth auths & reversals
- Feat(issuing): simulate clearing

2023-06-07 13:57 UTC, martinseco requested changes
Left some comments

2023-06-08 10:38 UTC, armando-ibarra-cko commented on src/CheckoutSdk/Issuing/IssuingClient.CardTesting.cs
> +            CheckoutUtils.ValidateParams("authorizationId", authorizationId, "cardAuthorizationRequest",
The name of the string should be "cardAuthorizationReversalRequest"

2023-06-08 10:38 UTC, armando-ibarra-cko commented on src/CheckoutSdk/Issuing/Testing/Requests/CardAuthorizationClearingRequest.cs
> +        public int Amount { get; set; }
primitives requires `?`

2023-06-08 10:38 UTC, armando-ibarra-cko commented on src/CheckoutSdk/Issuing/Testing/Requests/CardAuthorizationIncrementingRequest.cs
> +        public int Amount { get; set; }
same here

2023-06-08 10:38 UTC, armando-ibarra-cko commented on src/CheckoutSdk/Issuing/Testing/Requests/CardAuthorizationReversalRequest.cs
> +        public int Amount { get; set; }
here

2023-06-08 12:42 UTC, martinseco approved these changes
Looks good! Just one small comment before merging

2023-06-08 12:42 UTC, martinseco commented on src/CheckoutSdk/Issuing/IssuingClient.CardTesting.cs
> +            CheckoutUtils.ValidateParams("authorizationId", authorizationId, "cardAuthorizationClearingRequest",
"cardAuthorizationClearingRequest" should be cardClearingAuthorizationRequest

2023-06-08 13:00 UTC, merged